//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Action_List.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acao
    {
        public int Id { get; set; }
        public System.DateTime Abertura { get; set; }
        public System.DateTime Prazo { get; set; }
        public Nullable<System.DateTime> Fechamento { get; set; }
        public string Acao1 { get; set; }
        public string Descricao { get; set; }
        public int Responsavel { get; set; }
        public string Status { get; set; }
        public string Observacoes { get; set; }
        public int ProjetoId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Projeto Projeto { get; set; }
    }
}
